# Generated by Django 5.0.4 on 2024-04-26 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
