# Generated by Django 5.0.4 on 2024-08-13 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='other_text',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('SC', 'Single Choice'), ('SA', 'Short Answer'), ('DT', 'Date')], default='MC', max_length=2),
        ),
    ]
