# Generated by Django 5.0.4 on 2024-08-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_choice_date_choice_other_text_question_q_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='other_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
