# Generated by Django 5.0.4 on 2024-08-14 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_vote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('SC', 'Single Choice'), ('SA', 'Short Answer'), ('DT', 'Date'), ('TM', 'Time')], default='MC', max_length=2),
        ),
    ]
